;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="BasicCharacter.PriorityMax",NewTagName="AnimMontagePriority.PriorityMax")
+GameplayTagRedirects=(OldTagName="BasicCharacter",NewTagName="AnimMontagePriority")
+GameplayTagList=(Tag="AnimMontagePriority",DevComment="Animation montage priority tags category")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.NPC",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.Player",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.Player.SwapWeapon",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.Player.ThrowWeapon",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.Player.TurnInPlace",DevComment="")
+GameplayTagList=(Tag="AnimMontagePriority.BasicCharacter.Player.UseItem",DevComment="")

